[workspace]
resolver = "3"
members = [
    "cli",
    "ui",
]

[workspace.package]
version = "1.6.0-alpha.3"
license = "GPL-3.0-or-later"
edition = "2024"
authors = [
    "Lily Hopkins <lily@hpkns.uk>",
    "Eden Turner <somebirb7190@gmail.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
