# Recommended: Specify your app ID *OR* your base resource path for more robust icon loading
app_id = "uk.hpkns.EvidenceAngel"
base_resource_path = "/uk/hpkns/EvidenceAngel/"

# List of icon names you found (shipped with this crate)
# Note: the file ending `-symbolic.svg` isn't part of the icon name.
icons = [
    "chevron-up-down-regular",
    "cross-large",
    "delete-filled",
    "folder-open-filled",
    "lightbulb",
    "menu",
    "plus",
    "text-bold",
    "text-italic",
    "code",
    "text-header-1-lines-caret-regular",
    "text-header-2-lines-caret-regular",
    "text-header-3-lines-caret-regular",
]
icon_folder = "icons"
