[package]
name = "angelmark"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
getset = "0.1.4"
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.11.1"
thiserror = "2.0.11"
tracing = "0.1.41"
