name: Check version is suitable for merge to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    container:
      image: docker.io/cimg/go:1.17

    steps:
      - name: Checkout this PR
        uses: actions/checkout@v4
      - name: Determine Cargo version of this PR
        id: version-pr
        run: |
          export CARGO_PKG_VERSION=$(awk -F '["=]' '/^\[(workspace.)?package\]/{p=1} p && /^version[[:space:]]*=/ {gsub(/"/, "", $3); print $3; p=0}' Cargo.toml)
          export CARGO_PKG_PRERELEASE=$([[ $CARGO_PKG_VERSION =~ -[0-9A-Za-z]+ ]] && echo "true" || echo "false")
          echo "CARGO_PKG_VERSION=${CARGO_PKG_VERSION}" >> $GITHUB_OUTPUT
          echo "CARGO_PKG_PRERELEASE=${CARGO_PKG_PRERELEASE}" >> $GITHUB_OUTPUT

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Determine Cargo version of main
        id: version-main
        run: |
          export CARGO_PKG_VERSION=$(awk -F '["=]' '/^\[(workspace.)?package\]/{p=1} p && /^version[[:space:]]*=/ {gsub(/"/, "", $3); print $3; p=0}' Cargo.toml)
          export CARGO_PKG_PRERELEASE=$([[ $CARGO_PKG_VERSION =~ -[0-9A-Za-z]+ ]] && echo "true" || echo "false")
          echo "CARGO_PKG_VERSION=${CARGO_PKG_VERSION}" >> $GITHUB_OUTPUT
          echo "CARGO_PKG_PRERELEASE=${CARGO_PKG_PRERELEASE}" >> $GITHUB_OUTPUT

      - name: Assert versions are different
        run: |
          go install github.com/davidrjonas/semver-cli@latest
          semver-cli greater ${{ steps.version-pr.outputs.CARGO_PKG_VERSION }} ${{ steps.version-main.outputs.CARGO_PKG_VERSION }}
